/* tslint:disable */
/* eslint-disable */
/**
 * RC中国-爱宠有卡
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ConsumerAccount,
    ConsumerAddress,
    Order,
    Pet,
    ProductVariant,
    Store,
    Subscription,
} from './';

/**
 * 
 * @export
 * @interface Consumer
 */
export interface Consumer {
    name: string;
    image: string;
    tencentAccount: ConsumerAccount;
    nickname?: string;
    phone?: string;
    level: string;
    points: number;
    key: string;
    version: string;
    createdAt: Date;
    createdBy: string;
    lastModifiedAt: Date;
    lastModifiedBy: string;
    lastLoginTime: Date;
    tenant: Array<Store>;
    addresses: Array<ConsumerAddress>;
    pets: Array<Pet>;
    tags: Array<string>;
    subscriptions: Array<Subscription>;
    coupons: Array<object>;
}


